version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mireadb
      - POSTGRES_USER=malixds
      - POSTGRES_PASSWORD=130603maxim
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mirea_trade
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Используйте DEBUG=0 в продакшене
    depends_on:
      - db

volumes:
  postgres_data:
