# Generated by Django 4.2.3 on 2023-07-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('skills', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(default='regular', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orders', models.IntegerField(default=0)),
                ('contact_link', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.CharField(max_length=500)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField()),
                ('created', models.DateField()),
                ('contact_link', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user')),
            ],
        ),
    ]
