# Generated by Django 4.2 on 2023-07-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_task_kind_task_subject_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
