# Generated by Django 4.2.3 on 2023-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_user_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(default='Новичок', max_length=20),
        ),
    ]
