# Generated by Django 4.2.3 on 2023-07-31 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_task_executor_alter_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to='polls.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contact_link',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
