# Generated by Django 4.2 on 2023-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_task_contact_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, default='free-icon-user-149071.png', null=True, upload_to='images/'),
        ),
    ]
