# Generated by Django 4.2 on 2023-09-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_comment_user_comment_author_comment_worker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='worker',
            new_name='commant_worker',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
    ]
