# Generated by Django 4.2 on 2023-09-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_comment_commant_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commant_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_comment', to='polls.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_of_comment', to='polls.userprofile'),
        ),
    ]
