# Generated by Django 4.2 on 2023-09-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_comment_commant_worker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commant_worker',
            new_name='comment_worker',
        ),
    ]
