# Generated by Django 4.2 on 2023-09-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_comment_author_alter_comment_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='description',
        ),
    ]
