# Generated by Django 4.2 on 2023-09-20 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_rename_text_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
