# Generated by Django 4.2 on 2023-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_comment_timestamp_userprofile_last_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='media/images/profile.png', null=True, upload_to='media/images/'),
        ),
    ]
