# Generated by Django 4.2 on 2023-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='mirea_trade/images/profile.png', null=True, upload_to='media/images/'),
        ),
    ]
