# Generated by Django 4.2 on 2023-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_task_status_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
