# Generated by Django 4.2 on 2023-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_task_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
