# Generated by Django 4.2 on 2023-10-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_task_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='report',
        ),
    ]
