# Generated by Django 4.2.3 on 2023-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_remove_task_feedback_task_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
